KR.Web_/Controllers/DesignerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KR.Business.Repositories;
using KR.Business.Entities;
using PagedList;
using KR.DbEF.Repositories;

namespace KR.Web.Controllers
{
    public class DesignerController : Controller
    {
        private static IDesigner<Designer> _Repositories;
        public DesignerController(IDesigner<Designer> Repositories)
        {
            _Repositories = Repositories;
        }

        
        [HttpGet]
        [Authorize]
        public ActionResult Index(int? page)
        {
            var List = _Repositories.GetList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(List.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Add(Designer designer)
        {
            if (ModelState.IsValid)
            {
                _Repositories.Save(designer);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var designer = _Repositories.GetbyId(id);
            if (designer == null)
                return RedirectToAction("Index");
            return View(designer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Designer customer)
        {
            if (ModelState.IsValid)
            {
                _Repositories.Edit(customer);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public JsonResult Delete(int id)
        {
            var customer = _Repositories.Delete(id);
            if (customer == null)
            {
                return Json(-1);
            }
            return Json(id);
        }

        [HttpGet]
        public ActionResult Info(int id)
        {
            var user = _Repositories.GetbyId(id);
            if (user == null)
                return RedirectToAction("Index");
            return View(user);
        }
    }
}

KR.Web_/Controllers/HomeController.cs
using KR.Business.Entities;
using KR.Business.ReportBilders;
using KR.Business.Repositories;
using KR.DbEF.Repositories;
using KR.Web_.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KR.DbEF;
using KR.Business.ExelHelpers;

namespace KR.Web_.Controllers
{
    public class HomeController : Controller
    {
        private static IZakaz<Zakaz> ZakazRepositories;
        private static IWork<Work> WorkRepositories;
        private static IZakazInfo<ZakazInfo, zakaz> ZakazInfoRepositories;
        private static ISingleOrder<SingleOrder> SingleOrderRepo;
        private static IDifficulties<Difficulties> DiffiicultsRepo;

        private static ExportRepositories ExportRepositories;

        public HomeController(IZakaz<Zakaz> _ZakazRepositories,
                              IWork<Work> _WorkRepositories,
                              IZakazInfo<ZakazInfo, zakaz> _ZakazInfoRepositories,
                              ISingleOrder<SingleOrder> _SingleOrderRepo,
                              IDifficulties<Difficulties> _DiffiicultsRepo)
        {
            ZakazRepositories = _ZakazRepositories;
            WorkRepositories = _WorkRepositories;
            ZakazInfoRepositories = _ZakazInfoRepositories;
            SingleOrderRepo = _SingleOrderRepo;
            DiffiicultsRepo = _DiffiicultsRepo;

            ExportRepositories = new ExportRepositories();
        }

        [Authorize]
        public ActionResult Index(int? page,
            string nameDesigner, string surnameDesigner,
            string nameCustomer, string surnameCustomer,
            int? OrderPrice,
            string startDate, string endDate)
        {
            string prise = String.Empty;

            if (String.IsNullOrEmpty(nameDesigner))
                nameDesigner = String.Empty;
            if (String.IsNullOrEmpty(surnameDesigner))
                surnameDesigner = String.Empty;

            if (String.IsNullOrEmpty(nameCustomer))
                nameCustomer = String.Empty;
            if (String.IsNullOrEmpty(surnameCustomer))
                surnameCustomer = String.Empty;

            if (OrderPrice != null)
                prise = OrderPrice.Value.ToString();

            if (String.IsNullOrEmpty(startDate))
                startDate = String.Empty;
            if (String.IsNullOrEmpty(endDate))
                endDate = String.Empty;
           
            var List = ZakazInfoRepositories.GetList(nameDesigner, surnameDesigner,
                                                     nameCustomer, surnameCustomer, prise, startDate, endDate);

            if (List == null)
                List = new List<ZakazInfo>();

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(List.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Info(int id)
        {
            var zakaz = SingleOrderRepo.GetbyId(id);
            if (zakaz == null)
                return RedirectToAction("Index");

            return View(zakaz);
        }

        [HttpGet]
        [Authorize(Roles = "admin, Designer")]
        public ActionResult Edit(int id)
        {
            var zakaz = ZakazRepositories.Get(id);
            return View(zakaz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, Designer")]
        public ActionResult Edit(Zakaz zakaz)
        {
            if (ModelState.IsValid)
            {
                var _zakaz = ZakazRepositories.Edit(zakaz);
                if (_zakaz != null)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(zakaz);
        }

        [HttpGet]
        [Authorize(Roles = "admin, Designer")]
        public ActionResult Add(int id)
        {
            var zakaz = new Zakaz();
            zakaz.land_id = id;
            return View(zakaz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, Designer")]
        public ActionResult Add(Zakaz zakaz)
        {
            if (ModelState.IsValid)
            {
                var _zakaz = ZakazRepositories.Save(zakaz);
                if (_zakaz != null)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(zakaz);
        }

        [HttpPost]
        [Authorize(Roles = "admin, Designer")]
        public JsonResult Delete(int id)
        {
            var zakaz = ZakazInfoRepositories.Delete(id);
            if (zakaz == null)
                Json(-1);

            return Json(id);
        }

        [HttpPost]
        [Authorize(Roles = "admin, Designer")]
        public JsonResult AddDifficults(int orderId, int difficultsId)
        {
            var add = DiffiicultsRepo.Save(orderId, difficultsId);
            return Json(add);
        }

        [HttpPost]
        [Authorize(Roles = "admin, Designer")]
        public JsonResult DeleteDifficults(int orderId, int difficultsId)
        {
            var add = DiffiicultsRepo.Remove(orderId, difficultsId);
            if (add == null)
                return Json(-1);
            return Json(add.id);
        }

        [HttpPost]
        [Authorize(Roles = "admin, Designer")]
        public JsonResult AddWork(int orderId, Work work)
        {
            var add = WorkRepositories.Save(orderId, work);
            return Json(add);
        }


        [HttpPost]
        [Authorize(Roles = "admin, Designer")]
        public JsonResult DeleteWork(int orderId, int workId)
        {
            var add = WorkRepositories.Remove(orderId, workId);
            if (add == null)
                return Json(-1);
            return Json(add.id);
        }



        [Authorize(Roles = "admin, Designer")]
        public ActionResult Reports()
        {
            return View();
        }

        [Authorize(Roles = "admin, Designer")]
        public FileResult GetAvgOrderReport(string Time)
        {
            var report = ZakazInfoRepositories.GetOrderReport(Time);
            var file = OrderDateReportBilders.GetReport(report);
            return File(file, "application/pdf", "report.pdf");
        }

        [Authorize(Roles = "admin, Designer")]
        public FileResult GetOrderReport(int id)
        {
            var report = ZakazInfoRepositories.GetReport(id);
            var file = OrderReportBilders.GetReport(report);
            return File(file, "application/pdf", "report.pdf");
        }

        [Authorize(Roles = "admin, Designer")]
        public FileResult GetExtraOrderReport(int Time, int size)
        {
            var report = ZakazInfoRepositories.GetExtraReport(Time, size);
            var file = ExtraOrderReportBilders.GetReport(report);
            return File(file, "application/pdf", "report.pdf");
        }

        [Authorize(Roles = "admin, Designer")]
        public FileResult GetExelDb()
        {
            var List = ExportRepositories.GetList();
            var file = ExportToExel.Download(List);
            return File(file, "application/vnd.ms-excel", "export.xlsx");
        }

    }
}

KR.Web_/Controllers/LandController.cs
using KR.Business.Entities;
using KR.Business.Repositories;
using KR.DbEF.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KR.Web.Controllers
{
    public class LandController : Controller
    {
        private static ICustomer<Customer> CustomerRepositories;
        private static ILand<Land> LandRepositories;
        public LandController(ICustomer<Customer> _Repositories, ILand<Land> _LandRepositories)
        {
            CustomerRepositories = _Repositories;
            LandRepositories = _LandRepositories;
        }

        public ActionResult Index()
        {
            return RedirectToAction("Index","Home",null);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Add(int id)
        {
            Land land = new Land();
            land.customer_id = id;
            return View(land);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Add(Land land)
        {
            if (ModelState.IsValid)
            {
                LandRepositories.Save(land);
                return RedirectToAction("Info", "Customer", new { id = land.customer_id });
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var land = LandRepositories.GetbyId(id);
            if (land == null)
                return RedirectToAction("Index", "Home", null);
            return View(land);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Land land)
        {
            if (ModelState.IsValid)
            {
                LandRepositories.Edit(land);
                return RedirectToAction("Info", "Customer", new { id= land.customer_id});
            }
            return View();
        }

        [HttpGet]
        public ActionResult Info(int id)
        {
            var land = LandRepositories.GetbyId(id);
            if(land ==null)
                return RedirectToAction("Index", "Home", null);
            return View(land);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public JsonResult Delete(int id)
        {
            var customer = LandRepositories.Delete(id);
            if (customer == null)
            {
                Json(-1);
            }
            return Json(id);
        }
    }
}

KR.Web_/Views/Home/Add.cshtml
@model KR.Business.Entities.Zakaz

@{
    ViewBag.Title = "Add";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Add</h2>


        @using (Html.BeginForm("Add","Home"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Zakaz</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.designer_id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.designer_id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.designer_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.land_id)

                @Html.HiddenFor(model => model.price)

                <div class="form-group">
                    @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

    </div>
</div>

KR.Web_/Views/Home/Edit.cshtml
@model KR.Business.Entities.Zakaz

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Edit</h2>


        @using (Html.BeginForm("Edit","Home"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Zakaz</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.designer_id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.designer_id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.designer_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.land_id)

                @Html.HiddenFor(model => model.price)

                <div class="form-group">
                    @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Edit" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

    </div>
</div>

KR.Web_/Views/Home/Index.cshtml
@model PagedList.IPagedList<KR.Business.Entities.ZakazInfo>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Index</h2>
        <div class="top-custom">

            <div>
                <button type="submit" class="btn btn-default btn-right" data-toggle="collapse" data-target="#demo">Search</button>
                @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                {
                    <div id="demo" class="collapse form-collapse">
                        <table class="tb">
                            <tr><td>Designer:</td></tr>
                            <tr><td>Name</td><td><input type="text" name="nameDesigner" /></td></tr>
                            <tr><td>Surname</td><td><input type="text" name="surnameDesigner" /></td></tr>
                        </table>
                        <table class="tb">
                            <tr><td>Customer:</td></tr>
                            <tr><td>Name</td><td><input type="text" name="nameCustomer" /></td></tr>
                            <tr><td>Surname</td><td><input type="text" name="surnameCustomer" /></td></tr>
                        </table>
                        <table class="tb">
                           
                            <tr>
                                <td>Start date</td>
                                <td><input type="date" name="startDate" /></td>
                                <td>End date</td>
                                <td><input type="date" name="endDate" /></td>
                            </tr>
                        </table>
                        <button type="submit" class="btn btn-default" data-toggle="collapse" data-target="#demo">Search</button>
                    </div>

                }
            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    <span>Designer</span>
                </th>
                <th>
                    <span>Customer</span>
                </th>
                <th>
                    <span>Price</span>
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr id="row_1_@item.zakaz.id">
                    <td>
                        @*@Html.DisplayFor(modelItem => item.designer.name)*@
                        @Html.ActionLink(item.designer.name, "Info", "Designer", new { id = item.designer.id }, null)
                        @Html.ActionLink(item.designer.surname, "Info", "Designer", new { id = item.designer.id }, null)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.customer.name)*@
                        @Html.ActionLink(item.customer.name, "Info", "Customer", new { id = item.customer.id }, null)
                        @Html.ActionLink(item.customer.surname, "Info", "Customer", new { id = item.customer.id }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.zakaz.price)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Info", new { id = item.zakaz.id })
                        @if (User.IsInRole("admin"))
                        {
                            <span>|</span>
                            @Html.ActionLink("Edit", "Edit", new { id = item.zakaz.id })                            <span>|</span>
                            @Html.ActionLink("Delete", "Delete", new { id = item.zakaz.id }, new { @class = "delete", id = "item_" + item.zakaz.id })
                        }
                    </td>
                </tr>
                <tr class="innerTR" id="row_2_@item.zakaz.id">
                    <td>
                        <span>Start Date:</span>
                        @Html.DisplayFor(modelItem => item.zakaz.start_time)
                        <br />
                        <span>End Date:</span>
                        @Html.DisplayFor(modelItem => item.zakaz.end_time)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

@Scripts.Render("~/bundles/Zakaz")

KR.Web_/Views/Home/Info.cshtml
@model KR.Business.Entities.SingleOrder

@{
    ViewBag.Title = "Info";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        @if (User.IsInRole("admin"))
        {
            using (Html.BeginForm("GetOrderReport", "Home", FormMethod.Get))
            {
                @Html.Hidden("id", Model.ZakazInfo.zakaz.id)
                <button class="btn btn-default">Get Report</button>
            }
        }
        @Html.HiddenFor(model => Model.ZakazInfo.zakaz.id, new { id = "orderId" })
        <div>
            <dl class="dl-horizontal"></dl>
        </div>
        <table>
            <tr class="ZakazDesigner">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.designer)<span>: </span>
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.designer.name, "Info", "Designer", new { id = Model.ZakazInfo.designer.id }, null)
                    @Html.ActionLink(Model.ZakazInfo.designer.surname, "Info", "Designer", new { id = Model.ZakazInfo.designer.id }, null)
                </td>
            <tr />

            <tr class="ZakazCustomer">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.customer)<span>: </span>
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.customer.name, "Info", "Customer", new { id = Model.ZakazInfo.customer.id }, null)
                    @Html.ActionLink(Model.ZakazInfo.customer.surname, "Info", "Customer", new { id = Model.ZakazInfo.customer.id }, null)
                <td>
            </tr>

            <tr class="ZakazLand">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land)
                </td>
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land.name)
                </td>
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land.addres)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.land.name, "Info", "Land", new { id = Model.ZakazInfo.land.id }, null)
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.land.addres, "Info", "Land", new { id = Model.ZakazInfo.land.id }, null)
                </td>
            </tr>
        </table>
        <div class="ZakazPrice">
            @Html.LabelFor(modelItem => Model.ZakazInfo.zakaz.price)<span>: </span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.price)
            <br />
            <div class="ZakazWork">

                @Html.LabelFor(modelItem => Model.ZakazInfo.work)<span>: </span>
                <button class="addNewWork btn btn-default" data-toggle="collapse" data-target="#demo">Add Work</button>
                <div id="demo" class="collapse">
                    <table class="table">
                        <tr>
                            <td>Count</td>
                            <td><input type="number" name="countt" id="countt" /></td>
                        </tr>
                        <tr>
                            <td>Type</td>
                            <td><input type="text" name="typee" id="typee" /></td>
                        </tr>
                        <tr>
                            <td>Price</td>
                            <td><input type="number" name="price" id="price" /></td>
                        </tr>
                        <tr><td><button id="addNewWork" class="btn btn-default">Add</button></td><td></td></tr>
                    </table>
                </div>
                @*@Html.ActionLink("Add new", "Add", "Work", new { id = Model.ZakazInfo.zakaz.id }, new { @class="addNewWork"})*@
                <table class="table">
                    <tr>
                        <th>@Html.LabelFor(modelItem => Model.ZakazInfo.work[0].countt)</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.ZakazInfo.work)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.countt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.typee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                            <td>
                                <span>@(item.countt * item.price)</span>
                            </td>
                            <td>
                                @if (User.IsInRole("admin"))
                                {
                                    @Html.ActionLink("Delete", "DeleteWork", "Home", null, new { id = item.id, @class = "deleteWork" })
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>


            <div class="ZakazDifficults">
                @Html.LabelFor(modelItem => Model.ZakazInfo.difficults)<span> : </span>
                <select id="newDifficults">
                    @foreach (var item in Model.AllPosibleDifficults)
                    {
                        <option value="@item.id">@item.subj</option>
                    }
                </select>
                <button id="addDifficults" class="btn btn-default">Add</button>
                <table class="table">
                    <tr>
                        <th>Type</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.ZakazInfo.difficults)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.subj)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                            <td>
                                @if (User.IsInRole("admin"))
                                {
                                    @Html.ActionLink("Delete", "DeleteDifficalties", "Home", null, new { id = item.id, @class = "deleteDifficults" })
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>

        </div>
        <div class="ZakazDate">
            <span>Start Date:</span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.start_time)
            <br />
            <span>End Date:</span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.end_time)
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ZakazInfo.zakaz.id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>

@Scripts.Render("~/bundles/OrderInfo")

KR.Web_/Views/Home/Reports.cshtml
@{
    ViewBag.Title = "Reports";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2 reports">
        <div class="OrderReports">
            @using (Html.BeginForm("GetAvgOrderReport", "Home", FormMethod.Get))
            {
                <span>Order land size and work count report</span><br />
                <label class="radio-inline">
                    <input checked type="radio" value="1" name="Time">All Time
                </label>
                <label class="radio-inline">
                    <input type="radio" value="2" name="Time">Year
                </label>
                <label class="radio-inline">
                    <input type="radio" value="3" name="Time">Month
                </label><br />
                <button type="submit" class="btn btn-default send">Get orders report</button>
            }
            <hr />
            @using (Html.BeginForm("GetExtraOrderReport", "Home", FormMethod.Get))
            {
                <span>Order</span><br />
                <span>By date:</span><br />
                <label class="radio-inline">
                    <input checked type="radio" value="1" name="Time">All Time
                </label>
                <label class="radio-inline">
                    <input type="radio" value="2" name="Time">Year
                </label>
                <label class="radio-inline">
                    <input type="radio" value="3" name="Time">Month
                </label><br />
                <span>By land size:</span><br />
                <label class="radio-inline">
                    <input checked type="radio" value="1" name="Size">All
                </label>
                <label class="radio-inline">
                    <input type="radio" value="2" name="Size">Less 1000
                </label>
                <label class="radio-inline">
                    <input type="radio" value="3" name="Size">Less 500
                </label><br />
                <button type="submit" class="btn btn-default send">Get order report</button>
            }
            <hr />
            @using (Html.BeginForm("GetExelDb", "Home", FormMethod.Get))
            {
                <span>Export to exel</span><br />
                <button type="submit" class="btn btn-default send">Get exel export file</button>
            }
        </div>
    </div>
</div>