KR.Web/Controllers/HomeController.cs
using KR.Business.Entities;
using KR.Business.ReportBilders;
using KR.Business.Repositories;
using KR.DbEF.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KR.Web.Controllers
{
    public class HomeController : Controller
    {
        //IZakaz<Zakaz> ZakazRepositories;
        ZakazInfoRepositories ZakazInfoRepositories;
        ZakazRepositories ZakazRepositories;
        SingleOrderRepositories SingleOrderRepo;
        DifficultsRepositories DiffiicultsRepo;
        WorkRepositories WorkRepositories;

        public HomeController()
        {
            ZakazInfoRepositories = new ZakazInfoRepositories();
            ZakazRepositories = new ZakazRepositories();
            SingleOrderRepo = new SingleOrderRepositories();
            DiffiicultsRepo = new DifficultsRepositories();
            WorkRepositories = new WorkRepositories();
        }

        public ActionResult Index(int? page, 
            string nameDesigner, string surnameDesigner,
            string nameCustomer, string surnameCustomer,
            string price, 
            string startDate, string endDate)
        {
            if (String.IsNullOrEmpty(nameDesigner))
                nameDesigner = String.Empty;
            if (String.IsNullOrEmpty(surnameDesigner))
                surnameDesigner = String.Empty;

            if (String.IsNullOrEmpty(nameCustomer))
                nameCustomer = String.Empty;
            if (String.IsNullOrEmpty(surnameCustomer))
                surnameCustomer = String.Empty;

            if (String.IsNullOrEmpty(price))
                price = String.Empty;

            if (String.IsNullOrEmpty(startDate))
                startDate = String.Empty;
            if (String.IsNullOrEmpty(endDate))
                endDate = String.Empty;

            var List = ZakazInfoRepositories.GetList(nameDesigner, surnameDesigner,
                                                     nameCustomer,  surnameCustomer, price,startDate,  endDate);

            if (List == null)
                List = new List<ZakazInfo>();

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(List.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Info(int id)
        {
            var zakaz = SingleOrderRepo.GetbyId(id);
            if (zakaz == null)
                return RedirectToAction("Index");

            return View(zakaz);
        }

        [HttpGet]
        public ActionResult Add(int id)
        {
            var zakaz = new Zakaz();
            zakaz.land_id = id;
            return View(zakaz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Zakaz zakaz)
        {
            if (ModelState.IsValid)
            {
                var _zakaz = ZakazRepositories.Save(zakaz);
                if (_zakaz != null)
                {
                    return RedirectToAction("Info", new { id = zakaz.id });
                }
            }
            return View(zakaz);
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var zakaz = ZakazInfoRepositories.Delete(id);
            if (zakaz == null)
                Json(-1);

            return Json(id);
        }

        public string Deletes(int id)
        {
            var zakaz = ZakazInfoRepositories.Delete(id);
            if (zakaz == null)
                return (-1).ToString();

            return (id).ToString();
        }


        [HttpPost]
        public JsonResult AddDifficults(int orderId, int difficultsId)
        {
            var add = DiffiicultsRepo.Save(orderId, difficultsId);
            return Json(add);
        }

        [HttpPost]
        public JsonResult DeleteDifficults(int orderId, int difficultsId)
        {
            var add = DiffiicultsRepo.Remove(orderId, difficultsId);
            if (add == null)
                return Json(-1);
            return Json(add.id);
        }

        [HttpPost]
        public JsonResult AddWork(int orderId, Work work)
        {
            var add = WorkRepositories.Save(orderId, work);
            return Json(add);
        }


        [HttpPost]
        public JsonResult DeleteWork(int orderId, int workId)
        {
            var add = WorkRepositories.Remove(orderId, workId);
            if (add == null)
                return Json(-1);
            return Json(add.id);
        }





        //========================

        public ActionResult Reports()
        {
            return View();
        }

        public FileResult GetAvgOrderReport(string Time)
        {
            var report = ZakazInfoRepositories.GetOrderReport(Time);
            var file = OrderDateReportBilders.GetReport(report);
            return File(file, "application/pdf", "report.pdf");
        }

        public FileResult GetOrderReport(int id)
        {
            var report = ZakazInfoRepositories.GetReport(id);
            var file = OrderReportBilders.GetReport(report);
            return File(file, "application/pdf", "report.pdf");
        }

    }
}

KR.Web/Controllers/WorkController.cs
using KR.Business.Entities;
using KR.Business.Repositories;
using KR.DbEF.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KR.Web.Controllers
{
    public class WorkController : Controller
    {
        IWork<Work> WorkRepositories;
        public WorkController()
        {
           // WorkRepositories = new WorkRepositories();
        }

        // GET: Work
        public ActionResult Index()
        {
            return RedirectToAction("Inde", "Home", null);
        }

        //[HttpGet]
        //public ActionResult Add(int id)
        //{
        //    var work = new Work();
        //    //work.
        //}
    }
}

KR.Web/Views/Home/AddCustomer.cshtml
@model KR.Business.Entities.Customer

@{
    ViewBag.Title = "Add";
}

<h2>CustomerAdd</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KR.Web/Views/Home/EditCustomer.cshtml
@model KR.Business.Entities.Customer

@{
    ViewBag.Title = "EditCustomer";
}

<h2>EditCustomer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KR.Web/Views/Home/Index.cshtml
@model PagedList.IPagedList<KR.Business.Entities.ZakazInfo>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Index</h2>
        <div class="top-custom">

            <div>
                <button type="submit" class="btn btn-default btn-left" data-toggle="collapse" data-target="#demo">Search</button>
                @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                {
                    <div id="demo" class="collapse form-collapse">
                        <table class="tb">
                            <tr><td>Designer:</td></tr>
                            <tr><td>Name</td><td><input type="text" name="nameDesigner" /></td></tr>
                            <tr><td>Surname</td><td><input type="text" name="surnameDesigner" /></td></tr>
                        </table>
                        <table class="tb">
                            <tr><td>Customer:</td></tr>
                            <tr><td>Name</td><td><input type="text" name="nameCustomer" /></td></tr>
                            <tr><td>Surname</td><td><input type="text" name="surnameCustomer" /></td></tr>
                        </table>
                        <table class="tb">
                            <tr><td>Price</td><td><input type="number" name="price" /></td></tr>
                            <tr>
                                <td>Start date</td>
                                <td><input type="date" name="startDate" /></td>
                                <td>End date</td>
                                <td><input type="date" name="endDate" /></td>
                            </tr>
                        </table>
                        <button type="submit" class="btn btn-default" data-toggle="collapse" data-target="#demo">Search</button>
                    </div>
                    
                }
            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    <span>Designer</span>
                </th>
                <th>
                    <span>Customer</span>
                </th>
                <th>
                    <span>Price</span>
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr id="row_1_@item.zakaz.id">
                    <td>
                        @*@Html.DisplayFor(modelItem => item.designer.name)*@
                        @Html.ActionLink(item.designer.name, "Info", "Designer", new { id = item.designer.id }, null)
                        @Html.ActionLink(item.designer.surname, "Info", "Designer", new { id = item.designer.id }, null)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.customer.name)*@
                        @Html.ActionLink(item.customer.name, "Info", "Customer", new { id = item.customer.id }, null)
                        @Html.ActionLink(item.customer.surname, "Info", "Customer", new { id = item.customer.id }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.zakaz.price)
                    </td>
                    <td>
                        @if (User.IsInRole("admin"))
                        {
                        @Html.ActionLink("Edit", "Edit", new { id = item.zakaz.id }) |
                        @Html.ActionLink("Details", "Info", new { id = item.zakaz.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.zakaz.id }, new { @class = "delete", id = "item_" + item.zakaz.id })
                        }
                    </td>
                </tr>
                <tr class="innerTR" id="row_2_@item.zakaz.id">
                    <td>
                        <span>Start Date:</span>
                        @Html.DisplayFor(modelItem => item.zakaz.start_time)
                        <br />
                        <span>End Date:</span>
                        @Html.DisplayFor(modelItem => item.zakaz.end_time)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

@Scripts.Render("~/bundles/Zakaz")

KR.Web/Views/Home/Info.cshtml
@model KR.Business.Entities.SingleOrder

@{
    ViewBag.Title = "Info";
}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        @Html.HiddenFor(model => Model.ZakazInfo.zakaz.id, new { id = "orderId" })
        <div>
            <dl class="dl-horizontal"></dl>
        </div>
        <table>
            <tr class="ZakazDesigner">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.designer)<span>: </span>
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.designer.name, "Info", "Designer", new { id = Model.ZakazInfo.designer.id }, null)
                    @Html.ActionLink(Model.ZakazInfo.designer.surname, "Info", "Designer", new { id = Model.ZakazInfo.designer.id }, null)
                </td>
            <tr />

            <tr class="ZakazCustomer">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.customer)<span>: </span>
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.customer.name, "Info", "Customer", new { id = Model.ZakazInfo.customer.id }, null)
                    @Html.ActionLink(Model.ZakazInfo.customer.surname, "Info", "Customer", new { id = Model.ZakazInfo.customer.id }, null)
                <td>
            </tr>

            <tr class="ZakazLand">
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land)
                </td>
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land.name)
                </td>
                <td>
                    @Html.LabelFor(modelItem => Model.ZakazInfo.land.addres)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.land.name, "Info", "Land", new { id = Model.ZakazInfo.land.id }, null)
                </td>
                <td>
                    @Html.ActionLink(Model.ZakazInfo.land.addres, "Info", "Land", new { id = Model.ZakazInfo.land.id }, null)
                </td>
            </tr>
        </table>
        <div class="ZakazPrice">
            @Html.LabelFor(modelItem => Model.ZakazInfo.zakaz.price)<span>: </span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.price)
            <br />
            <div class="ZakazWork">

                @Html.LabelFor(modelItem => Model.ZakazInfo.work)<span>: </span>
                <button class="addNewWork btn btn-default" data-toggle="collapse" data-target="#demo">Add Work</button>
                <div id="demo" class="collapse">
                    <table class="table">
                        <tr>
                            <td>Count</td>
                            <td><input type="number" name="countt" id="countt" /></td>
                        </tr>
                        <tr>
                            <td>Type</td>
                            <td><input type="text" name="typee" id="typee" /></td>
                        </tr>
                        <tr>
                            <td>Price</td>
                            <td><input type="number" name="price" id="price" /></td>
                        </tr>
                        <tr><td><button id="addNewWork" class="btn btn-default">Add</button></td><td></td></tr>
                    </table>
                </div>
                @*@Html.ActionLink("Add new", "Add", "Work", new { id = Model.ZakazInfo.zakaz.id }, new { @class="addNewWork"})*@
                <table class="table">
                    <tr>
                        <th>@Html.LabelFor(modelItem => Model.ZakazInfo.work[0].countt)</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.ZakazInfo.work)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.countt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.typee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                            <td>
                                <span>@(item.countt * item.price)</span>
                            </td>
                            <td>
                                @if (User.IsInRole("admin"))
                                {
                                    @Html.ActionLink("Delete", "DeleteWork", "Home", null, new { id = item.id, @class = "deleteWork" })
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>


            <div class="ZakazDifficults">
                @Html.LabelFor(modelItem => Model.ZakazInfo.difficults)<span> : </span>
                <select id="newDifficults">
                    @foreach (var item in Model.AllPosibleDifficults)
                    {
                        <option value="@item.id">@item.subj</option>
                    }
                </select>
                <button id="addDifficults" class="btn btn-default">Add</button>
                <table class="table">
                    <tr>
                        <th>Type</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.ZakazInfo.difficults)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.subj)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                            <td>
                                @if (User.IsInRole("admin"))
                                {
                                    @Html.ActionLink("Delete", "DeleteDifficalties", "Home", null, new { id = item.id, @class = "deleteDifficults" })
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>

        </div>
        <div class="ZakazDate">
            <span>Start Date:</span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.start_time)
            <br />
            <span>End Date:</span>
            @Html.DisplayFor(modelItem => Model.ZakazInfo.zakaz.end_time)
        </div>
        <p>
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.ZakazInfo.zakaz.id }) |
            }
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>

@Scripts.Render("~/bundles/OrderInfo")

KR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Land Dez", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    Tables
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu menu-right">
                    <li>@Html.ActionLink("Order", "Index", "Home")</li>
                    <li>@Html.ActionLink("Customer", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Designer", "Index", "Designer")</li>
                    @*<li>@Html.ActionLink("Zakaz", "Index", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>